# Generated by Django 3.2.6 on 2021-08-05 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookcatalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readinglistbook',
            old_name='list',
            new_name='reading_list',
        ),
    ]
