# Generated by Django 3.2.6 on 2021-08-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookcatalog', '0002_rename_list_readinglistbook_reading_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='readinglist',
            name='list_name',
            field=models.CharField(default='Books', max_length=100),
        ),
    ]
