# Generated by Django 3.2.6 on 2021-08-10 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookcatalog', '0005_alter_review_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review',
            new_name='comments',
        ),
    ]
