# Generated by Django 3.2.6 on 2021-08-30 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookcatalog', '0010_alter_review_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookcatalog.reader')),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookcatalog.reader')),
                ('friends_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookcatalog.friendslist')),
            ],
        ),
    ]
