# Generated by Django 3.2.6 on 2021-09-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookcatalog', '0011_friend_friendslist'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
