# Generated by Django 3.2.6 on 2021-09-03 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookcatalog', '0014_alter_review_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readinglist',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookcatalog.reader'),
        ),
    ]
